### ISSUE TITLE
解析rdb快照文件获取所有key

### ISSUE THREAD

**Issue by Myshiner** [xiepaup/dbatools#4]
我把rdb文件复制到别的机器，然后想用redis-cli-new命令解析所有的key，就是想看看都有哪些key，这个如何操作？是直接redis-cli-new --scan --rdb 111.rdb >> 111.log 这样吗？

**Comment by xiepaup** [comment]
目前不得行哦， rdb 解析可以参考下这里： https://github.com/lanfang/redis-analyzer

**Comment by xiepaup** [comment]
parse-rdb   Parses rdb file from local or redis server directly
  这部分

**Comment by travishao** [comment]
我用java  cmd调用 redis-cli 获取数据，--scan就是拿不到  别的可以拿到
